"""add_mode_to_audit_model

Revision ID: 5fa4292f7ff9
Revises: 7ef34d9986d5
Create Date: 2026-09-25 20:07:28.863257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa4292f7ff9'
down_revision: Union[str, Sequence[str], None] = '7ef34d9986d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('mode', sa.String(), server_default='remote', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'mode')
    # ### end Alembic commands ###
